### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Yomamaeatstoes** [Euphillya/WorldEdit-Folia#1]
WorldEdit-Folia Build failure

https://mclo.gs/gKOTCP1

**Comment by Euphillya** [comment]
I've removed Fabric, Forge and Sponge from the build. It can also be downloaded here : https://github.com/Euphillya/WorldEdit-Folia/releases

**Comment by Euphillya** [comment]
Im try with action github, and no error : Okay thank you so much^^ don't worry, you can send when it is onvenient of you

**Comment by Yomamaeatstoes** [comment]
It still fails to build on ubuntu for me? 

https://mclo.gs/b1rSpbU

**Comment by Euphillya** [comment]
You must be doing something wrong because me, github works and we never have fabric that loads.

**Comment by Yomamaeatstoes** [comment]
Hello, I believe this was N error on my part. In any case, I created a PR, but this looks really far along. Do you plan on doing an PR instead?

**Comment by Euphillya** [comment]
I just modified it to make it compatible on Folia, but it is no longer compatible with Paper 1.20.1 before #42 and spigot currently. I'd have to check whether or not Folia is used first, and then put two possibilities each time, unless I'm redoing a class for schedules.

**Comment by Euphillya** [comment]
I'll have to give Fabric etc... to make a possible PR to WE

**Comment by Euphillya** [comment]
@Yomamaeatstoes I've finally got my new PC, I was able to redo the build correctly with forge etc... And no more problems! https://github.com/Euphillya/WorldEdit-Folia/commit/e23eee62e0c508f17c2e53a602cecf01a971be1e

**Comment by Yomamaeatstoes** [comment]
> @Yomamaeatstoes I've finally got my new PC, I was able to redo the build correctly with forge etc... And no more problems! [e23eee6](https://github.com/Euphillya/WorldEdit-Folia/commit/e23eee62e0c508f17c2e53a602cecf01a971be1e)

That’s amazing to hear!

I was thinking of 3 scenerios. 

1: I leave my PR up as a draft, While you submit yours and see if it gets accepted. 


2: You do a PR to my WE since I already have a draft open for review. 


3: none of these happen and you have a separate plan.

**Comment by Euphillya** [comment]
@Yomamaeatstoes I've already tried to submit, but they don't want to have a dependency on top of it (Energy I use).
So the best thing would be for you to retrieve my modifications and submit them without Energie, I think.

**Comment by Yomamaeatstoes** [comment]
> @Yomamaeatstoes I've already tried to submit, but they don't want to have a dependency on top of it (Energy I use). So the best thing would be for you to retrieve my modifications and submit them without Energie, I think.

Oh if I add you as a contributor on my fork, would you like to work on this with us?

**Comment by Euphillya** [comment]
I wouldn't be able to put all my time into it, but I can help without any problem.

**Comment by Yomamaeatstoes** [comment]
> I wouldn't be able to put all my time into it, but I can help without any problem.

That is good to hear! Do you have a discord?

**Comment by Euphillya** [comment]
yes my tag is : euphyllia_bierque
and my discord is : https://discord.gg/Dws42V5uX5
