### ISSUE TITLE
Unable to use it with 1.20.4

### ISSUE THREAD

**Issue by Reddishye** [Euphillya/WorldEdit-Folia#2]
### WorldEdit Version

Tested with all releases

### Platform Version

git-Folia-"ec6b172"

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Unable to use it with 1.20.4, tested with all releases.

### Expected Behavior

To work lol

### Reproduction Steps

1. Install any release on the latest folia build of 1.20.4

**Comment by Reddishye** [comment]
Might be because is an edited version of folia adding lithium patches? lol

**Comment by Reddishye** [comment]
anyways it shouldn't give error, stills folia

**Comment by Euphillya** [comment]
Can you tell me exactly what is happening?

**Comment by Reddishye** [comment]
It says it does not detect the version / worldedit does not support that version

**Comment by Euphillya** [comment]
Send all logs startup

**Comment by Euphillya** [comment]
Last version : https://github.com/Euphillya/WorldEdit-Folia/commit/13d1b3f160b680565d92c5ae577fdcb54e260dd4 work on folia 1.20.6 
![image](https://github.com/Euphillya/WorldEdit-Folia/assets/26461373/b1a64a60-b52d-407f-9b87-cdeaef811aef)

**Comment by Reddishye** [comment]
Im using it on 1.20.4, I realised it must be something of the version, because I tried with an older version of folia and it works, although it starts without errors, shows a warning saying the version is not supported, and when doing any action, says editing is disabled.

**Comment by Euphillya** [comment]
You use which version of Worldedit? Impossible to reproduce...

**Comment by Reddishye** [comment]
Sorry for the delay on the response, I tried with all the released available on this repo, one by one

**Comment by Euphillya** [comment]
Try this version: https://github.com/Euphillya/WorldEdit-Folia/releases/tag/7.3.0-1.20.4-Folia
